# apiVersion: v1
# kind: Service
# metadata:
#   name: texttranslator-service
# spec:
#   type: NodePort
#   ports:
#     - name: http
#       protocol: TCP
#       port: 5002
#       targetPort: 5002
#       nodePort: 30001
#   selector:
#     app: texttranslator-deplyoment


apiVersion: v1
kind: Service
metadata:
  name: texttranslator-service
spec:
  type: LoadBalancer
  selector:
    app:  texttranslator-deplyoment
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 5002